spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            remove-abandoned-timeout: 180
            initial-size: 10
            min-idle: 5
            max-active: 20
            max-wait: 90000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
        master:
            url: jdbc:TAOS://td.master.com:6030/test?charset=UTF-8&locale=en_US.UTF-8
            username: root
            password: taosdata
            driver-class-name: com.taosdata.jdbc.TSDBDriver
        slave1:
            url: jdbc:TAOS://td.slave.com:6030/test?charset=UTF-8&locale=en_US.UTF-8
            username: root
            password: taosdata
            driver-class-name: com.taosdata.jdbc.TSDBDriver